### ISSUE TITLE
Test Failure: nodeos_chainbase_allocation_if_test

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#246]
[nodeos_chainbase_allocation_if_test](https://github.com/AntelopeIO/spring/actions/runs/9403899442/job/25902099390?pr=245#step:4:1285)

**Comment by heifner** [comment]
Since LIB moves so quickly in savanna this test is now a bit flaky.

The test creates two snapshots and verifies they are the same. It attempts to generate the snapshot on the same block, but it failed because one snapshot was generated on block 122 and the other on block 123.

I think a simple sleep(1) before the first snapshot to make sure it has all the blocks is all that is needed.

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/actions/runs/9408382330/job/25916647179
