### ISSUE TITLE
Stricter checks in apply_diff and compile warnings

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#723]
`index` in `apply_diff` is a signed int and can be negative. Currently index is only checked not greater than the size. 

This also results in warnings in numerous places as `apply_diff` is in a header file which is included by a number of files:

```
libraries/libfc/include/fc/container/ordered_diff.hpp:111:35: warning: comparison of integer expressions of different signedness: ‘std::ptrdiff_t’ {aka ‘long int’} and ‘std::vector<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
...
ibraries/libfc/include/fc/container/ordered_diff.hpp:119:26: warning: comparison of integer expressions of different signedness: ‘std::tuple_element<0, std::pair<int, char> >::type’ {aka ‘int’} and ‘std::vector<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
```

**Comment by arhag** [comment]
Conclusion:
+ This is not actually a bug that can be exploited by even malicious producers to cause problems on the chain. The bad blocks would already be rejected during the block apply stage. (There is no undefined behavior because we got lucky. The standard says the comparison of `std::size_t` with `std::ptrdiff_t` promotes the `std::ptrdiff_t` to `std::size_t`, and so that would cause the resulting value to be so large that it would trigger to assert that checks it is less than the container size.)
+ We do wish to cleanup the `FC_ASSERTS` in `apply_diff` to get rid of the compiler warnings and make it more obvious that this is actually safe.
+ The cleanup does not make the blockchain validation any more or less strict, so this is not a blockchain validation protocol change. However, a bad block may now be rejected at an earlier stage during block header validation rather than waiting until the block is applied.
+ We can actually enforce that the indices in `diff.remove_indexes` and `diff.insert_indexes` are strictly monotonically increasing (and provide meaningful error messages if they do not) without changing the blockchain validation protocol either. So we should do so.
