### ISSUE TITLE
Some issues after the spring upgrade

### ISSUE THREAD

**Issue by wangjiangw** [AntelopeIO/spring#907]
hi team, after the spring upgrade, we found our rpc node will not run normally, there are some issues we have found :
1、the io and network cost have been raised too high to sync the block normally 
2、the rpc will not response when the node is syncing, even the simplest interface get_info.

we want to know what happened and how to fix it correctly, we have upgraded to v1.0.2, but still not work. the count of transactions in eos mainnet blocks now are not great increased, what is the main reason causes the downgrade of the performance of the node ？
![image](https://github.com/user-attachments/assets/8d0756b8-6cd8-463d-8b09-947d3820a808)

![image](https://github.com/user-attachments/assets/a4cd2b41-4faf-4820-96a9-eb5b4d31cb2b)

**Comment by bhazzard** [comment]
This is likely due to the large influx on data into EOS network RAM due to usage. The number of transactions did not significantly increase, but those transactions were writing a lot of data. So much data, that the state database has multiplied in size.

As a result, nodes ideally need to have 192GB of RAM minimum, 256GB recommended. Alternatively, if you have sys-admin skills, some node operators have been successful running with significant lower physical memory by leveraging tmpfs and swap file.
